src/components/atoms/Badge/index.test.js
src/components/atoms/Button/index.test.js
src/components/atoms/GenericAtom/index.test.js
src/components/atoms/Heading/index.test.js
src/components/atoms/HorizontalRule/index.test.js
src/components/atoms/Icon/index.test.js
src/components/atoms/Input/index.test.js
src/components/atoms/Label/index.test.js
src/components/atoms/Link/index.test.js
src/components/atoms/List/index.test.js
src/components/atoms/LogoImage/index.test.js
src/components/atoms/Paragraph/index.test.js
src/components/atoms/Select/index.test.js
src/components/atoms/TableCell/index.test.js
src/components/atoms/TableRow/index.test.js
src/components/molecules/Blockquote/index.test.js
src/components/molecules/Feature/index.test.js
src/components/molecules/Field/index.test.js
src/components/molecules/GenericMolecule/index.test.js
src/components/molecules/IconButton/index.test.js
src/components/molecules/IconLink/index.test.js
src/components/molecules/Table/index.test.js
src/components/organisms/Footer/index.test.js
src/components/organisms/Header/index.test.js

I've done small refectoring just like in issue #22.

Small refactoring (issue #22)

---

src/components/atoms/Heading/index.js

Replace rem by em on Heading

---

src/components/atoms/Tooltip/index.js
src/components/atoms/Tooltip/index.test.js
src/components/organisms/Hero/index.js

Animate Tooltip

---

package.json
src/components/atoms/Icon/icons/close.svg
src/components/globals.js
src/components/molecules/Modal/index.js
src/components/molecules/Modal/index.test.js
yarn.lock

Add Modal component

---

package.json
test/actionsMock.js

[redux] Add actions mock

---

package.json

Update eslint to version 3.14.0

---

src/components/atoms/Input/index.js
src/components/atoms/Link/index.js
src/components/molecules/Feature/index.js
src/components/molecules/IconButton/index.js
src/components/molecules/IconLink/index.js
src/components/molecules/Modal/index.js
src/components/molecules/Table/index.js
yarn.lock

Follow the Object Rest Destructuring specification

---

.storybook/webpack.config.js
package.json
src/components/atoms/Icon/index.js
src/components/atoms/LogoImage/index.js
webpack.config.js
yarn.lock

This should cover the basic setup. It doesn't look like storybook has supports webpack 2 so I converted the config to webpack 1 for storybook.

Initial conversion to support Webpack 2

---

package.json
src-clean/index.js
src/index.js
yarn.lock

Remove react-router-scroll

---

.gitignore

Also please check other branches

Remove yarn-error.log

---

src/store/social/sagas.js
src/store/social/sagas.test.js

Added some try/catch blocks.
Fix #79

Fix redux social login error

---

src/store/resource/actions.js
src/store/resource/actions.test.js
src/store/resource/reducer.js
src/store/resource/reducer.test.js
src/store/resource/sagas.js
src/store/resource/sagas.test.js
src/store/resource/selectors.js
src/store/resource/selectors.test.js

This is an example of a `resource` store with all CRUD operations.

Add resource store

---

src-clean/index.js
src/index.js

Thanks to @kybarg's comment: https://github.com/diegohaz/arc/pull/129#discussion_r103093588

Enable HMR on react-router

---

.babelrc
.storybook/.babelrc
package.json
yarn.lock

`babel-preset-latest` is showing warnings asking it.

Replace babel-preset-latest for babel-preset-env

---

src/components/molecules/Slider/index.js
src/components/molecules/Slider/index.stories.js
src/components/molecules/Slider/index.test.js

Created an input range component that follows arc style. 
_This is my first commit to a project, so I hope I'm doing this right!_
Closes #78

Add Slider (input range) component

---

README.md

Saw this repo – liked the project and saw you're looking for help on this so I thought this would make a good first pr for me. Cheers!

Fix some small readme typos and phrasing.

---

.eslintrc
.storybook/webpack.config.js
package.json
webpack/webpack-dev-server.js
webpack/webpack.config.js

To be more consistent with other branches

Put webpack files on webpack folder

---

src-clean/config.js
src/config.js
webpack/env.js

Did the same on the [fullstack] branch so that it resolves properly on linux/unix and windows based systems without need for manual changes.

[redux-ssr] changed 0.0.0.0 to localhost

---

src-example/containers/PostForm.js
src-example/store/post/actions.js
src-example/store/post/actions.test.js
src-example/store/resource/actions.js
src-example/store/resource/actions.test.js
src-example/store/status/middleware.js
src-example/store/status/middleware.test.js
src-example/store/status/sagas.js
src-example/store/status/sagas.test.js

And make it possible to return a promise when dispatching doneable actions

[redux] Use done instead of resolve/reject on actions

---

.babelrc
package.json
yarn.lock

Combines with `styled-components` v2 for a better debugging experience, minification etc.

Add babel-plugin-styled-components

---

src/components/index.js

Revert "Improved resolution of circularly dependent components"

---

src-example/components/organisms/FeatureList/index.js

These are minor errors but they are both rather prominent in the page.

Update index.js to fix two spelling mistakes
